# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-03 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('start_date', models.CharField(max_length=45)),
                ('end_date', models.CharField(max_length=45)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_user_reverse', to='logreg.Userdb')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_travel_reverse', to='logreg.Userdb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_user_reverse', to='logreg.Userdb')),
            ],
        ),
    ]
