# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-03 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_travel_reverse', to='first_app.TravelPlan'),
        ),
    ]
